Fix markdowns
Piturnah/gex pull request #4
Opened 2022-08-17 13:50 UTC by kianmeng

Found via this command:

    markdownlint *.md --disable MD013 MD033 MD024

See a detailed description of the rules is available at
https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md

2022-08-17 14:09 UTC, Piturnah requested changes
Just a few notes

2022-08-17 14:09 UTC, Piturnah commented on CHANGELOG.md
>  - Diff items can be expanded or collapsed with <kbd>Tab</kbd>
Please remove the changes to `CHANGELOG.md`, I am content with its current formatting style.

2022-08-17 14:09 UTC, Piturnah commented on README.md
Great :+1:

2022-08-18 15:42 UTC, Piturnah commented
Thank you for making those changes, and thanks for your contribution!

2022-08-18 15:42 UTC, merged

2022-08-19 05:24 UTC, kianmeng commented
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

2022-08-19 15:19 UTC, Piturnah commented
Released in 0.3 :tada: